# Promise

## 异步编程的背景知识
* JS引擎是基于单线程（single threaded）事件循环（event loop）构建的，同一时刻只能执行一个代码块
* 事件循环：它是引擎中的一段程序，负责监控代码的执行并管理任务队列
* 常规的2种异步模型：
  * 事件模型：适合处理简单的交互，需要跟踪每个事件的事件目标，而且要保证事件在添加事件处理程序之后触发，如常规的浏览器端的鼠标点击等事件
  * 回调模式：`Node.js`改进了异步模型，将回调函数作为参数传入，当异步任务完成后，会向队列末尾添加新任务，该任务包括回调函数及其相应的参数
* 事件模型和回调模式对于处理复杂问题不是很灵活，比如同时执行多个异步操作，结束时通知你。回调模式更容易陷入嵌套回调的深渊

```js
// 事件模型
let button = document.getElementById("my-btn");
button.onclick = function(event) {
  console.log("clicked");
}
// 回调模式
readFile("package.json", function(err, contents) {
  if (err) {
    throw err;
  }
  conosle.log(contents);
});
```

## Promise的基础知识
* `Promise`相当于异步操作结果的占位符，
* 内部属性`[[PromiseState]]`被用来表示`Promise`的3种状态：
  * "pending": 处理中...
  * "fulfilled": 处理成功
  * "rejected": 处理失败
* 不可以用编程的方式检测`Promise`的状态，只能通过`then()`方法或`catch()`方法来对状态的改变进行处理
  * `then(fulfilled(),rejected())`：2个参数都是可选的，为状态变为成功或失败时的回调，并且会接收到相关的成功或失败的数据
  * `catch(rejected())`: 1个参数是可选的，为状态变为失败时的回调，并且会接收到相关失败的数据
* 如果不给`Promise`添加拒绝处理程序，那所有的失败则自动会被忽略
* `thenable`对象：实现了上述`then()`方法的对象，所有的`Promise`都是`thenable`对象，但并非所有的`thenable`都是`Promise`

```js
let promise = readFile("package.json");
promise.then(function() {
  console.log("success");
}, function() {
  console.log("error");
});
promise.catch(function() {
  console.log("error");
});
// catch 等同于
promise.then(null, function() {
  console.log("error");
});
```

### 创建未完成的Promise
* 通过构造函数创建新的Promise，只接受一个参数：包含初始化Promise代码的执行器(execurtor)函数
* 执行器函数包括2个参数：
  * `resolve()` 方法：执行器成功完成时调用
  * `reject()` 方法：执行器失败时调用

```js
let fs = require("fs");
function readFile(filename) {
  return new Promise(function(resolve, reject) {
    fs.readFile(filename, {encoding: "utf-8"}, function(err, contents) {
      if (err) {
        reject(err);
        return;
      }
      reslove(contents);
    });
  });
}
let promise = readFile("package.json");
promise.then(function(contents) {
  console.log(contents);
}, function(err) {
  console.log(err.message);
});
```

### 创建已处理的Promise
* `Promise.resolve()`: 只接受一个参数，返回一个完成态的`Promise`
* `Promise.reject()`: 只接受一个参数，返回一个拒绝态的`Promise`
* 如果向`Promise.resolve()`和`Promise.reject()`传入一个`Promise`，则这个`Promise`会被直接返回
* `Promise.resolve()`和`Promise.reject()`都可以接受非Promise的thenable对象作为参数

```js
let promise = Promise.resolve(42);
promise.then(function(value) {
  console.log(value);
});
let promise = Promise.reject(42);
promise.catch(function(value) {
  console.log(value);
});
// thenable
let thenable = {
  then(resolve, reject) {
    resolve(42);
    // reject(42);
  }
}
let promise = Promise.resolve(thenable);
promise.then(function(value) {
  console.log(value); // 42
});
// 或者
promise.catch(function(value) {
  console.log(value); // 42
});
```

### 执行器错误
每个执行器都隐藏一个`try-catch`块，会捕获错误并传入拒绝处理程序，只有当拒绝处理程序存在则会记录抛出的错误，否则会被忽略掉

```js
let promise = new Promise(function(resolve, reject) {
  throw new Error("Explosion"); 
  // 等同于
  try {
    throw new Error("Explosion");
  } catch (ex) {
    reject(ex);
  }
});
promise.catch(function(err) {
  console.log(err.message); // "Explosion"
});
```

## 全局的Promise拒绝处理
`Promise`的特性很难检测一个`Promise`是否被处理过，在没有拒绝处理程序的情况下拒绝一个`Promise`, 不会提示失败信息，也不会报错。
* Node.js环境的拒绝处理：
  * `unhandledRejection`: 在一个事件循环中，当Promise被拒绝，并且没有提供拒绝处理程序时被调用，回调函数2个参数: 错误对象和被拒绝的Promise
  * `rejectionHandled`: 在一个事件循环中，当promise被拒绝，在事件循环后，再提供拒绝处理程序时被调用，回调函数1个参数:即被拒绝的Promise
  * 
* Browser环境的拒绝处理：
  * `unhandledrejection`: 在一个事件循环中，当Promise被拒绝，并且没有提供拒绝处理程序时被调用
  * `rejectionhandled`: 在一个事件循环中，当promise被拒绝，在事件循环后，再提供拒绝处理程序时被调用
  * 2个方法的回调接收包含以下3个属性的事件对象作为参数：
    * type: 事件名称：unhandledrejection和rejectionhandled
    * reason: 来自Promise的拒绝值
    * promise: 被拒绝的Promise对象

```js
// Node.js
let rejected;
process.on('unhandledRejection', function(reason, promise) {
  console.log("unhandledRejection===");
  console.log(reason.message);
  console.log(rejected === promise);
});
process.on('rejectionHandled', function(promise) {
  console.log("rejectionHandled===");
  console.log(rejected === promise);
});
rejected = Promise.reject(new Error("Explosion！"));
setTimeout(function() {
  rejected.catch(function(value) {
    console.log(value.message);
  });
}, 1000);
// 最终输出
// unhandledRejection===
// Explosion！
// true
// rejectionHandled===
// true
// Explosion！

// Browser
let rejected;
window.onunhandledrejection = function(event) {
  console.log(event.type);
  console.log(event.reason.message);
  console.log(rejected === event.promise);
};
window.onrejectionhandled = function(event) {
  console.log(event.type);
  console.log(event.reason.message);
  console.log(rejected === event.promise);
};
rejected = Promise.reject(new Error("Explosion！"));
setTimeout(function() {
   rejected.catch(function(value) {
     console.log(value.message);
   });
}, 1000);
// 最终输出
// "unhandledrejection"
// "Explosion！"
// true
// "Explosion！"
// "rejectionhandled"
// "Explosion！"
// true
```

## 串联Promise
* 每次调用`then()`或者`catch()`方法，实际上创建并返回了另一个`Promise`，只有当第一个`Promise`完成或拒绝后，第二个才会被解决

```js
let p1 = new Promise(function(resolve, reject) {
  resolve(42);
});
p1.then(function(value) {
  console.log(value); // 42
})
  .then(function() { // 这个then前面的Promise是p1.then()返回的Promise
    console.log("finish");
  });
```

### 捕捉错误
* Promise链可以捕获错误，务必在Promise链的末尾留有一个拒绝处理程序以确保能够正确处理所有可能发生的错误

```js
let p1 = new Promise(function(resolve, reject) {
  throw new Error("Explosion!");
});
p1.catch(function(err) {
  console.log(err.message); // Explosion!
  throw new Error("Boom!");
}).catch(function(err) { // 这个catch前面的Promise是p1.catch()返回的Promise
  console.log(err.message); // Boom!
});
```

### Promise链的返回值
Promise链的重要特性就是给下游的Promise传值，如果在处理程序中指定一个返回值(`return`)，则可以沿着这条链继续传递数据

```js
let p1 = new Promise(function(resolve, reject) {
  reject(42);
});
p1.catch(function(value) {
  console.log(value); // 42
  return value + 1;
})
  .then(function(value) {
    console.log(value); // 43
  });
```

### 在Promise链中返回Promise
如果Promise链返回给下游的不是数据，而是Promise对象，则需要额外的步骤来确定下一步怎么走。

```js
let p1 = new Promise(function(resolve, reject) {
  resolve(42);
});
let p2 = new Promise(function(resolve, reject) {
  resolve(43);
});
p1.then(function(value) {
  console.log(value); // 42
  return p2;
})
  .then(function(value) { // 这个then前面的promise不是p2, 而是p1.then()返回的promise, 等待p2处理完成或拒绝后调用相应的处理程序
    console.log(value); // 43
  });
// 等同于
let p3 = p1.then(function(value) {
  console.log(value); // 42
  return p2;
})
p3.then(function(value) { 
  console.log(value); // 43
  });
```

## 响应多个Promise
* `Promise.all()`: 只接受一个参数并返回一个Promise，参数是一个含有多个受监视Promise的可迭代对象
  * 只有当可迭代对象中的所有Promise都解决后，返回的Promise才会被解决，完成处理程序的结果是一个包含解决值的数组，顺序按照Promise被解决的顺序存储
  * 只要有一个被拒绝，返回的Promise立即被拒绝，不会等到所有的Promise都完成，拒绝处理程序总是接受一个值而非数组，该值来自于被拒绝Promise的拒绝值
* `Promise.race()`: 只接受一个参数并返回一个Promise，参数是一个含有多个受监视Promise的可迭代对象
  * 参数Promise之间会竞选，如果先解决的是已完成的Promise,则返回已完成Promise，如果先解决的是已拒绝的Promise，则返回已拒绝的Promise
  * 只要有一个Promise被解决，返回的Promise就被解决，无须等到所有Promise都完成，虽然其它Promise最终会完成，但结果都被忽略掉了

```js
// all
let p1 = new Promise(function(resolve, reject) {
  resolve(42);
});
let p2 = new Promise(function(resolve, reject) {
  resolve(43);
});
let p3 = new Promise(function(resolve, reject) {
  resolve(44);
});
let p4 = Promise.all([p1,p2,p3]);
p4.then(function(value) {
  console.log(Array.isArray(value)); // true
  console.log(value[0]); // 42
  console.log(value[1]); // 43
  console.log(value[2]); // 44
});
p1 = Promise.reject(45);
p4 = Promise.all([p1,p2,p3]);
p4.catch(function(value) {
  console.log(Array.isArray(value)); // false
  console.log(value); // 45
});

// race
let p1 = Promise.resolve(42);
let p2 = new Promise(function(resolve, reject) {
  resolve(43);
});
let p3 = new Promise(function(resolve, reject) {
  resolve(44);
});
let p4 = Promise.race([p1,p2,p3]);
p4.then(function(value) {
  console.log(value); // 42
});
p1 = Promise.reject(45);
p4 = Promise.race([p1,p2,p3]);
p4.catch(function(value) {
  console.log(value); // 45
});
```

## Promise继承
* 可以定义派生类来扩展Promise的功能
* 静态方法会被继承，因此，派生类也拥有`resolve()`，`reject()`, `all()`, `race()`等这4个静态方法
* `resolve()`和`reject()`方法通过`Symbol.species`属性来决定返回Promise的类型，因此它们返回的是派生类的实例
  * 如果将内建Promise实例传入，返回的也是派生类的实例
  * 如果传入派生类的实例，则直接返回

```js
class MyPromise extends Promise {
  success(resolve, reject) {
    return this.then(resolve, reject);
  }
  error(reject) {
    return this.catch(reject);
  }
}
let promise = new Promise(function(resolve, reject) {
  resolve(42);
});
promise.success(function(value) {
  console.log(value); // 42
}).error(function(value) {
  console.log(value);
});
let p2 = MyPromise.resolve(promise); // p2为MyPromise的实例
p2.success(function(value) {
  console.log(value); // 42
});
console.log(p2 instanceof MyPromise); // true
```

## 基于Promise的异步任务执行
* 用Promise和生成器重写第8章用生成器和回调函数的方式完成的读取文件的操作
* 二者的区别：
  * 让读取文件返回一个`Promise`，而不是一个回调函数
  * 递归函数中，通过`then`和`catch`方法来处理`Promise`的返回值，以便进一步的处理

```js
let fs = require("fs");
function readFile(filename) {
  return new Promise(function(resolve, reject) {
    fs.readFile(filename, function(err, contents) {
      if (err) {
        reject(err);
        return;
      }
      resolve(contents);
    });
  });
};
function run(taskDef) {
  let task = taskDef(); // 创建迭代器
  let result = task.next(); // 开始执行任务
  (function step() {
    if (!result.done) {
      let promise = Promise.resolve(result.value); // 如果结果不是一个promise,将结果包裹为一个promise
      promise.then(function(value) {
              result = task.next(value);
              step();
            })
            .catch(function(error) {
              result = task.throw(error);
              step();
            });
      }
  })();
}
run(function*() {
  let contents = yield readFile("package.json");
  doSomethingWith(contents);
  console.log("done");
});
```
### async, await语法
* `async`: async标记的函数代替生成器，表示该函数以异步模式运行
* `await`: await代替yield来调用函数，表示调用的函数应该返回一个promise，否则响应应该被包裹在Promise中，如果被拒绝则应该抛错，否则通过Promise来返回值

```js
(async function() {
  let contents = await readFile("package.json");
  doSomethingWith(contents);
  console.log("done");
});
```